version: "3.7"
services:
  frontendshell:
    build:
      context: .
      dockerfile: frontend.shell.Dockerfile
    ports:
      - 8096:4000
  frontendefa:
    build:
      context: .
      dockerfile: frontend.efa.Dockerfile
    ports:
      - 8094:80
  frontendbooking:
    build:
      context: .
      dockerfile: frontend.booking.Dockerfile
    ports:
      - 8095:80

