version: "3.7"
services:
  frontend:
    image: blackforestsolutions/dravelopsfrontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8094:80"
  hvv:
    image: blackforestsolutions/dravelopsfrontend:${VERSION_TAG}-hvv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8094:80"
    environment:
      - CUSTOMER=hvv
  bw:
    image: blackforestsolutions/dravelopsfrontend:${VERSION_TAG}-bw
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8094:80"
    environment:
      - CUSTOMER=bw
